// Generates docs/TOOLS.md from the tool definitions in server/tools.js.
//   node scripts/gen-docs.mjs          write the file
//   node scripts/gen-docs.mjs --check  exit 1 if the file is out of date (CI)
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { TOOLS } from '../server/tools.js';

const GROUPS = [
  ['Status, tabs and navigation', ['browser_status', 'browser_tabs', 'browser_navigate']],
  ['Seeing the page', ['browser_snapshot', 'browser_screenshot', 'browser_get_content']],
  ['Interacting', ['browser_click', 'browser_hover', 'browser_type', 'browser_press_key', 'browser_select_option', 'browser_scroll', 'browser_wait_for', 'browser_upload_file', 'browser_handle_dialogs', 'browser_evaluate']],
  ['Frontend debugging', ['browser_audit_layout', 'browser_inspect', 'browser_set_viewport', 'browser_inject_css', 'browser_console', 'browser_network', 'browser_network_body']],
  ['Scraping', ['browser_extract', 'browser_scrape']],
];

const byName = new Map(TOOLS.map((t) => [t.name, t]));
const grouped = new Set(GROUPS.flatMap(([, n]) => n));
const missing = TOOLS.map((t) => t.name).filter((n) => !grouped.has(n));
if (missing.length) { console.error(`Add these tools to a group in scripts/gen-docs.mjs: ${missing.join(', ')}`); process.exit(1); }

const type = (s) => {
  if (!s) return '';
  if (s.enum) return s.enum.map((e) => `\`${e}\``).join(' \\| ');
  if (s.type === 'array') return `${type(s.items) || s.items?.type}[]`;
  if (s.anyOf) return s.anyOf.map(type).join(' \\| ');
  return s.type || 'object';
};
const cell = (s) => String(s ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ');

let md = `# Tool reference

<!-- Generated by scripts/gen-docs.mjs from server/tools.js. Do not edit by hand: run \`npm run docs\`. -->

Pagewright exposes ${TOOLS.length} MCP tools. Every tool that acts on a page accepts an optional \`tabId\`; without it, the tool uses the tab the agent last opened or selected, otherwise the active tab.

Elements are targeted with a \`ref\` from \`browser_snapshot\` (preferred) or a \`selector\`: CSS, \`text=Visible text\`, \`text="Exact text"\` or \`xpath=//path\`. Selectors also search open shadow DOM.

`;
for (const [title, names] of GROUPS) {
  md += `- [${title}](#${title.toLowerCase().replace(/[^a-z0-9 ]/g, '').replace(/ /g, '-')})\n`;
}
for (const [title, names] of GROUPS) {
  md += `\n## ${title}\n`;
  for (const name of names) {
    const t = byName.get(name);
    md += `\n### \`${name}\`\n\n${t.description}\n`;
    const props = Object.entries(t.inputSchema.properties || {});
    if (!props.length) { md += '\nNo parameters.\n'; continue; }
    const req = new Set(t.inputSchema.required || []);
    md += '\n| Parameter | Type | Description |\n|---|---|---|\n';
    for (const [p, s] of props) {
      const def = s.default !== undefined ? ` Default: \`${JSON.stringify(s.default)}\`.` : '';
      md += `| \`${p}\`${req.has(p) ? ' (required)' : ''} | ${type(s)} | ${cell(s.description)}${def} |\n`;
    }
  }
}

const file = new URL('../docs/TOOLS.md', import.meta.url);
if (process.argv.includes('--check')) {
  const current = existsSync(file) ? readFileSync(file, 'utf8') : '';
  if (current !== md) { console.error('docs/TOOLS.md is out of date. Run: npm run docs'); process.exit(1); }
  console.log('docs/TOOLS.md is up to date');
} else {
  writeFileSync(file, md);
  console.log(`wrote docs/TOOLS.md (${TOOLS.length} tools)`);
}
